name: Build Dart Shared Library
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            postfix: win
          - os: ubuntu-latest
            postfix: linux
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - run: dart pub get
        working-directory: ./scripts/build_helpers
      - name: Build Dart
        run: dart ./scripts/build_helpers/bin/build_dart.dart
      - uses: threeal/cmake-action@v1.3.0
      - name: Build Shared Library
        run: cmake --build build --config release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: libs-${{ matrix.postfix }}
          path: |
            ./build/src/Release/
            ./build/src/*.so
  